### ISSUE TITLE
migrate to next

### ISSUE THREAD

**Issue by lynii12** [lynii12/youtube-shorts-clone#5]
## 目的

- 路由
- ssr. bundle size
- api
  - [其他好處](https://nextjs.org/docs/app/building-your-application/upgrading/from-vite#why-switch)
- 練習 next

## 相關資源

- [migration 文件](https://nextjs.org/docs/app/building-your-application/upgrading/from-vite)

## Tasks

- [x] 完成 migration 文件的步驟
- [x] 區分哪些要做 server componet 哪些 client component，考量有用到樣式，`window` 等 client 端的取得
- [x] api 改由 next 提供，不另開 api server
